//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using PaymentTerminalService.Model;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace PaymentTerminalService.Web.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class PaymentTerminalServiceControllerBase : System.Web.Http.ApiController
    {
        /// <summary>
        /// Discover terminals, available connections, and current selection
        /// </summary>
        /// <returns>List of discovered terminals, their connection options, and the currently selected terminal</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("terminals")]
        public abstract System.Threading.Tasks.Task<TerminalCatalogResponse> GetTerminals();

        /// <summary>
        /// Get current selected terminal + connection
        /// </summary>
        /// <returns>Selected terminal</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("terminals/selected")]
        public abstract System.Threading.Tasks.Task<SelectedTerminalResponse> GetSelectedTerminal();

        /// <summary>
        /// Select terminal + connection (activates terminal implementation; may apply initial settings)
        /// </summary>
        /// <returns>Selected terminal updated and activated</returns>
        [System.Web.Http.HttpPut, System.Web.Http.Route("terminals/selected")]
        public abstract System.Threading.Tasks.Task<SelectedTerminalResponse> SelectTerminal([System.Web.Http.FromBody] SelectTerminalRequest body);

        /// <summary>
        /// Get settings for selected terminal/connection
        /// </summary>
        /// <returns>Settings payload</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("terminals/selected/settings")]
        public abstract System.Threading.Tasks.Task<TerminalSettings> GetSelectedTerminalSettings();

        /// <summary>
        /// Get the latest status result for the selected terminal
        /// </summary>
        /// <returns>Latest status result</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("terminals/selected/status")]
        public abstract System.Threading.Tasks.Task<TerminalStatus> GetSelectedTerminalStatus();

        /// <summary>
        /// Get current terminal session information (status history for current session, most recent first)
        /// </summary>
        /// <returns>All status results for the current session (most recent first)</returns>
        [System.Web.Http.HttpGet, System.Web.Http.Route("terminals/selected/session")]
        public abstract System.Threading.Tasks.Task<TerminalSessionResponse> GetSelectedTerminalSession();

        /// <summary>
        /// Start purchase (sequential)
        /// </summary>
        /// <returns>Operation accepted and started (poll status)</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/purchase")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> StartPurchase([System.Web.Http.FromBody] PurchaseRequest body);

        /// <summary>
        /// Start refund (sequential)
        /// </summary>
        /// <returns>Operation accepted and started (poll status)</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/refund")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> StartRefund([System.Web.Http.FromBody] RefundRequest body);

        /// <summary>
        /// Start reversal (sequential)
        /// </summary>
        /// <returns>Operation accepted and started (poll status)</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/reversal")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> StartReversal([System.Web.Http.FromBody] ReversalRequest body);

        /// <summary>
        /// Abort current transaction (if possible)
        /// </summary>
        /// <returns>Abort requested (poll status)</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/abort")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> AbortTransaction();

        /// <summary>
        /// Activate loyalty detection session (poll status)
        /// </summary>
        /// <returns>Loyalty activate accepted</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/loyalty/activate")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> LoyaltyActivate([System.Web.Http.FromBody] LoyaltyActivateRequest body);

        /// <summary>
        /// Deactivate loyalty detection session (poll status)
        /// </summary>
        /// <returns>Loyalty deactivate accepted</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/loyalty/deactivate")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> LoyaltyDeactivate([System.Web.Http.FromBody] BaseActionRequest body);

        /// <summary>
        /// Respond to an active prompt
        /// </summary>
        /// <returns>Prompt response accepted (poll status)</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/prompt")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> RespondToPrompt([System.Web.Http.FromBody] PromptResponseRequest body);

        /// <summary>
        /// Notify service that the transaction was processed by the calling entity
        /// </summary>
        /// <returns>Confirmation accepted</returns>
        [System.Web.Http.HttpPost, System.Web.Http.Route("terminals/selected/confirm")]
        public abstract System.Threading.Tasks.Task<OperationAccepted> ConfirmTransaction([System.Web.Http.FromBody] TransactionConfirmRequest body);

    }

    


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765